// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDi8VDy-OewzBVY8i7B5CD7rECdGnsOYs',
    appId: '1:1070587279819:web:ae12c98bf018b836da9e4e',
    messagingSenderId: '1070587279819',
    projectId: 'nearme-ai-8123d',
    authDomain: 'nearme-ai-8123d.firebaseapp.com',
    storageBucket: 'nearme-ai-8123d.firebasestorage.app',
    measurementId: 'G-ZWQ4DFM08X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GFXiQDKm9bWO0HvKpMnh4moDHAFHHsk',
    appId: '1:1070587279819:android:7b28af9519982edfda9e4e',
    messagingSenderId: '1070587279819',
    projectId: 'nearme-ai-8123d',
    storageBucket: 'nearme-ai-8123d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5BxHY-RLpGeqbv5A0dNcNEbexU7kzJfM',
    appId: '1:1070587279819:ios:3887f8a49ce9e9c6da9e4e',
    messagingSenderId: '1070587279819',
    projectId: 'nearme-ai-8123d',
    storageBucket: 'nearme-ai-8123d.firebasestorage.app',
    iosBundleId: 'com.billion.nearmeai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5BxHY-RLpGeqbv5A0dNcNEbexU7kzJfM',
    appId: '1:1070587279819:ios:93be20f3b97d5eabda9e4e',
    messagingSenderId: '1070587279819',
    projectId: 'nearme-ai-8123d',
    storageBucket: 'nearme-ai-8123d.firebasestorage.app',
    iosBundleId: 'com.example.nearmeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDi8VDy-OewzBVY8i7B5CD7rECdGnsOYs',
    appId: '1:1070587279819:web:9a7431179d340493da9e4e',
    messagingSenderId: '1070587279819',
    projectId: 'nearme-ai-8123d',
    authDomain: 'nearme-ai-8123d.firebaseapp.com',
    storageBucket: 'nearme-ai-8123d.firebasestorage.app',
    measurementId: 'G-HL57PGR5WS',
  );
}
