import 'package:flutter/material.dart';//Flutter UI framework.
import 'app.dart'; // Main app widget.
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

Future<void> main() async {//App entry point, this starts the Flutter application.
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const NearMeApp());
}



